apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
        volumeMounts:
        - name: webdata
          mountPath: "/usr/share/nginx/html"
      volumes:
      - name: webdata
        persistentVolumeClaim:
          claimName: whatever
